name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      - name: node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # - name: installing
      #   run: npm ci

      # publish to gh pages
      - name: publishing documents
        uses: peaceiris/actions-gh-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./data
